### ISSUE TITLE
Restricted to Distributions 0.21-0.23 prevents use of BlackBoxOptim#master

### ISSUE THREAD

**Issue by dlakelan** [anthofflab/RobustAdaptiveMetropolisSampler.jl#23]
I tried to install BlackBoxOptim#master and it wants Distributions 0.24 or larger, but RobustAdaptiveMetropolisSampler#master wants 0.21-0.23 so they can't work together.

I suspect it'd be easy to get RAM package to use the latest Distributions, so hopefully it can un-pin these versions and be used with more recent Distributions.jl

**Comment by davidanthoff** [comment]
Should be fixed on `master`, I'll tag a new release soon.
